development:
  clients:
    default:
      database: sachmem_forum_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: sachmem_forum_test
      hosts:
        - localhost:27017

production:
  clients:
    default:
      database: sachmem_forum_development
      hosts:
        - localhost:27017
